version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      #- MYSQL_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      #- POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      #- POSTGRES_PASSWORD=password